% rename all PDF files to match the paper structure:

fM = 0;
if ~exist('./figures/','dir')
    mkdir('./figures/')
end

sourceNames = {'infectionMatrix-imageSc.pdf',...
    'AreaPFU.pdf',...
    'phiLinearRegressions.pdf',...
    'allHotspotsLamBMovers.pdf',...
    'HotSpotClusters@0.01-allMutations.pdf',...
    'HotSpotClusters@0.01-completeResistanceMutants.pdf',...
    'plotOneLagExample19a.pdf',...
    'plotOneLagExamplewt.pdf',...
    'allRYTOplots.pdf',...
    'YieldAndRateCorrelation.pdf',...
    'YieldAndRateCorrelationAllData.pdf',...
    'relativeFitness.pdf',...
    'findResistantRmaxTOsAndTUs.pdf',...
    'findResistantGrowthRateTOsAndTUs.pdf',...
    'findResistantKmTOsAndTUs.pdf',...
    'GrowthRatePlotForWT.pdf',...
    'GrowthRatePlotFor56a.pdf',...
    'GrowthRatePlotFor26a.pdf',...
    'exampleMatchingPoints.pdf',...
    'exampleMatching.pdf',...
    'modularityPhiMatrix.pdf',...
    'modularityPhiGraph.pdf',...
    '2btoWTmatch2.pdf',...
    '2btoWTmatch1.pdf'};

targetNames = {'Figure2A.pdf',...
    'Figure2B.pdf',...
    'Figure3partial_AndA2.pdf',...
    'Figure5Apartial_AndA3.pdf',...
    'Figure5Btop.pdf',...
    'Figure5Bbottom.pdf',...
    'Figure6Atop.pdf',...
    'Figure6Abottom.pdf',...
    'Figure6BandCpartial_AndA4.pdf',...
    'Figure7Apartial_AndA5.pdf',...
    'Figure7B.pdf',...
    'Figure7C.pdf',...
    'Figure8A.pdf',...
    'Figure8B.pdf',...
    'Figure8C.pdf',...
    'Figure9A.pdf',...
    'Figure9B.pdf',...
    'Figure9C.pdf',...
    'FigureA7A.pdf',...
    'FigureA7B.pdf',...
    'FigureA8A.pdf',...
    'FigureA8B.pdf',...
    'FigureA10A.pdf',...
    'FigureA10B.pdf'};

N = length(sourceNames);
for j = 1:N
    if exist(['./figures/',sourceNames{j}],'file')
        movefile(['./figures/',sourceNames{j}],...
            ['./figures/',targetNames{j}])
        fM = fM + 1;
    end
end

if exist('./figures/56atoWTmatch1.pdf','file')
    movefile('./figures/56atoWTmatch1.pdf','./figures/unused/56atoWTmatch1.pdf')
	fM = fM + 1;
end

if exist('./figures/56atoWTmatch2.pdf','file')
    movefile('./figures/56atoWTmatch2.pdf','./figures/unused/56atoWTmatch2.pdf')
	fM = fM + 1;
end

%%

disp(['Moved ',num2str(fM),' figure (PDF) files, named to match paper figures']);

